package:
  name: autordf
  version: "{{ environ['CONDA_PACKAGE_VERSION_TAG'] }}"

source:
  path: ../

build:
  number: 0
  string: py{{ python|replace(".", "") }}

requirements:
   build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - boost
    - pybind11
    - cmake
    - pkg-config
    - python ={{ python }}
   run:
    - python ={{ python }}
    - boost
    - pybind11
   host:
    - python ={{ python }}


test:
  imports:
    - autordf_py

about:
  home: 'https://github.com/ariadnext/AutoRDF'
  summary: 'AutoRDF Python binding'
