package:
  name: autordf
  version: '1.0.0'

source:
  path: ../

requirements:
   build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - boost
    - pybind11
    - cmake
    - pkg-config
   host:
    - python={{ python }}
   run:
    - python={{ python }}

test:
  imports:
    - autordf_py

about:
  home: 'https://github.com/ariadnext/AutoRDF'
  summary: 'AutoRDF Python binding'
