package:
  name: autordf
  version: '1.0.0'

build:
  number: 1
  string: '3c0e99c6'
  missing_dso_whitelist:
    - '*/ld-linux-x86-64.so.2'
    - '*/libc.so.6'
    - '*/libm.so.6'
    - '*/libgcc_s.so.1'
    - '*/libstdc++.so.6'
  script_env:
    - AUTORDF_BUILD_DIR
    - IRMA_INSTALL_DIR

requirements:
  build:
    - python=3.9
    - pip
  run:
    - python=3.9

test:
  imports:
    - autordf_py

about:
  home: 'https://github.com/ariadnext/AutoRDF'
  summary: 'AutoRDF Python binding'
